### PR TITLE
Random generation

### PR DESCRIPTION
**Pull request by itanne99**
@djs93 If the code looks good please merge it into master!

### CODE REVIEW

**Comment by itanne99** [comment]
idk why coveralls is being annoying. Just let it be for now

**Review by djs93 — CHANGES_REQUESTED** [review]
The project spec says to throw an error when passed an empty array, I suggest adding the checks but it's not the most important thing ever

**Comment by itanne99** [comment]
I'll add it. It's not hard

**Review by djs93 — APPROVED** [review]
Looks good!

**Pull request merged**
